### ISSUE TITLE
React example does not work

### ISSUE THREAD

**Issue by mtmetra** [ardatan/meteor-webpack#14]
Since version 0.0.4_6 the React example renders nothing in the web browser (chrome).
The web server seems to work properly.

**Comment by royGil** [comment]
Working fine for me..
Did you try the current version of the example?

**Comment by mtmetra** [comment]
Yes, but updating the ardatan:webpack version of the react example to 0.0.4_8.

**Comment by ardatan** [comment]
I was working on path declarations in order to detect the output files in virtual file system, so `dev-server` package doesn't work in case of different path definitions (outputPath), because it just looks absolute root path. So, it looks `contentBase` and `output.path` definitions instead.

**Comment by mtmetra** [comment]
Now it works fine.
Thanks.
