### ISSUE TITLE
Accounts hooks broken after re-compilation

### ISSUE THREAD

**Issue by ardatan** [ardatan/meteor-webpack#15]
`webpack-dev-server` package handles methods and publications by keeping native ones and deleting rest, but Accounts hooks are not overwritten but duplicated in every re-compilation. So it causes `accounts` methods might become broken (login, resetPassword etc...). In this case, `devServer` can be removed in `serverConfig` as a workaround.
`Accounts.validateLoginAttempt` and `Accounts.validateNewUser` etc...

**Comment by royGil** [comment]
Does it happen with other packages too?
And what do you mean by **the accounts package becomes broken**? Can you give an example?

**Comment by ardatan** [comment]
For example;
Accounts.validateLoginAttempt is a callback hook, and this method registers a new hook when you call it like;
```js
  Accounts.validateLoginAttempt(() => {});
``` 
But if you do this twice, it will register two callbacks for single hook. Unfortunately, it doesn't override the existing one.
When our package reruns the projects, it registers same function as a different hook in every recompilation. Then, two or more duplicate hooks exist.

**Comment by royGil** [comment]
Well, that's really weird - do you have any idea what causes this to happen?

Seems like we have to find a way to "clean" the server between recompilations
