### ISSUE TITLE
Importing Blaze templates?

### ISSUE THREAD

**Issue by dhamaniasad** [ardatan/meteor-webpack#19]
Hi. First of all, I'd like to thank you for making this package. I've searched far and wide and am so extremely grateful to have stumbled across this project when I did. 

I'm new to Webpack having never used it before. How would one go about importing a Blaze template into the client entry point? 

Importing the html file throws this error: 
```
Uncaught Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <template name="App_body">
```

**Comment by dhamaniasad** [comment]
I was able to make some progress on this using the [spacebars-loader](https://github.com/xamfoo/spacebars-loader) package. However, adding that package resulted in a `Template not defined` error thrown in the browser console as I had removed `blaze-html-templates`. Adding that back in throws this error:
```
=> Started proxy.
=> Errors prevented startup:

   While determining active plugins:
   error: conflict: two packages included in the app (templating-compiler and
   ardatan:webpack) are both trying to handle *.html
```

I'm using both React and Blaze in my project, any ideas on how I could proceed @ardatan ?

**Comment by ardatan** [comment]
If you use this webpack package, you cannot use other compiler packages, and I had never consider about blaze support which may not work this package as well.
If you really don’t need Webpack with Meteor, you can kee using Meteor’s own packages.
Finally, this is not an issue. Please use stackoverflow, gitter or other similar platforms for your questions; this section on GitHub is for issues, bugs and other stuff.
Thanks.

**Comment by s7dhansh** [comment]
Too late to the party, but those who wish to do this can use https://github.com/settlin/node-monorepo/tree/master/spacebars-loader, via the procedure mentioned therein.

**Comment by dc165015** [comment]
@s7dhansh you save my days!

**Comment by s7dhansh** [comment]
@dc165015 good that it works for you!
There are still some problems that I have not been able to figure out till now. Sometimes the hot update does not work (times out, despite giving a high time out value), and the only option is to force a meteor reload (either restarting or simply changing some dummy things in webpack config). Because of this webpack is still unusable in my huge project that contains both blaze and react. Let me know if yo uface similiar issues, we can figure something out together.

**Comment by dc165015** [comment]
@s7dhansh I am working on a AngularIonic/Meteor project which combines of 3 sub-projects: client/api/admin. And I don't use Meteor client, but only meteor packages. So there is no hot update yet.  Thank you!
