### ISSUE TITLE
error: unknown package in top-level dependencies: ardatan:webpack-dev-middleware

### ISSUE THREAD

**Issue by filipenevola** [ardatan/meteor-webpack#2]
Hello, I can't find this package `ardatan:webpack-dev-middleware` on atmospherejs
https://atmospherejs.com/?q=webpack-dev-middleware

I tried to run your React example and got this error:
```
[[[[[ ~/Documents/filipe/ws/meteor-webpack/examples/react ]]]]]

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: unknown package in top-level dependencies: ardatan:webpack-dev-middleware
   
=> Your application has errors. Waiting for file change.
```
Maybe you still have to publish it?

**Comment by filipenevola** [comment]
It's solved! :wink: 

I'm testing the process overall, probably I'll get back here soon with more questions

Thanks again!

**Comment by ardatan** [comment]
Thank you I am waiting for your feedback!
