### ISSUE TITLE
How To Run After Compilation

### ISSUE THREAD

**Issue by stolinski** [ardatan/meteor-webpack#20]
This might seem like a dumb question, but how do you run your site after compilation. Is the intention to run through webpack or through Meteor.

For clarification, I'm running `webpack -w` and things are compiling fine, but should I be then running `meteor` as well to fire up the server?

**Comment by ardatan** [comment]
You need to call `meteor` only.
BTW, this section is for bugs and other similar issues. Please use gitter or stackoverflow for support.
