### ISSUE TITLE
.babelrc Ignored With Babel 7.0.0-beta & babel-loader 8.0.0-beta

### ISSUE THREAD

**Issue by stolinski** [ardatan/meteor-webpack#22]
Steps to reproduce: 

Clone and run: https://github.com/stolinski/meteor-webpack-test

You should be seeing an unexpected token error on the first < in jsx.

Same repo compiled fine with example versions of babel but after upgrading the .babelrc file is ignored. This doesn't seem to be a webpack issue though, because if you tell webpack to watch with `webpack -w` everything compiles correctly. The .babelrc file is only ignored when running `meteor` to build.

**Comment by stolinski** [comment]
Yah. It works with rc 12 and the older Babel loader.

**Comment by ardatan** [comment]
Ok, then I will investigate this issue.

**Comment by ardatan** [comment]
Somehow the new babel-loader is not compatible w/ Meteor. If you are using new version of Meteor, Meteor's client bundle cannot be injected to HTML. You can use the older version for now.

**Comment by ardatan** [comment]
Could you try to run the following command and try again?
```
meteor update babel-compiler ecmascript modules
```

**Comment by ardatan** [comment]
This problem is gone after last updates in both meteor and babel-runtime.
