### ISSUE TITLE
after runnig react example I get ReferenceError: Package is not defined

### ISSUE THREAD

**Issue by nikhilgoswami** [ardatan/meteor-webpack#26]
Steps to reproduce:
 go into examples react  
 run meteor npm install
 run meteor

**Comment by ardatan** [comment]
I need more details such as;
- Where do you get this error?
-- If it is browser; which browser are you working on?
-- If it is server; what is your Operating System?
- What is the whole stack of this error?

**Comment by nikhilgoswami** [comment]
in browsers console firefox it disappears after few refresh or restart I didn't check on chrome

**Comment by nikhilgoswami** [comment]
![error](https://user-images.githubusercontent.com/6419060/41448352-c50bfb02-7077-11e8-9e30-c01a51ddd869.png)

**Comment by ardatan** [comment]
When HMR is enabled, Meteor will load Webpack's client bundle asynchronously; this is a known problem that I'm still working on; the same situation exists in server as well.
I recommend you to disable HMR or use chrome until we fix it.

**Comment by finder** [comment]
I think that my error above was actually from trying to use the webpack dev server instead of meteor. While I'm still having issues with meteor, I think that the above was fixed by using "meteor run"

**Comment by ardatan** [comment]
That's normal, because Meteor loads its bundle independently from Webpack's.
I'm closing this issue, then.
