### ISSUE TITLE
Possible to build client side to static files, and run the meteor server side separately?

### ISSUE THREAD

**Issue by vephinx** [ardatan/meteor-webpack#32]
I would like to compile the client side to static files so that I can bundle them in a chrome extension. I would then like to run the meteor server on its own. I thought that this project would help me do this,  but I am not sure how. 

I can compile the react example with webpack by doing `npx webpack --config webpack.config.js` but running the index.html page gives me the error `Uncaught ReferenceError: Package is not defined`.

**Comment by ardatan** [comment]
I am sorry but this project
