### ISSUE TITLE
Is possible to use latest babel packages with meteor-webpack?

### ISSUE THREAD

**Issue by filipenevola** [ardatan/meteor-webpack#35]
Hello, I tried to update these dependencies
```
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
```
to use the latest at @babel/ but then I got an error saying that babel-core is missing and it is really missing because I replaced by @babel/core

I think this error in coming from babel-loader, maybe babel-loader is not ready yet or I need to use some beta version of it?

Thanks

**Comment by ardatan** [comment]
I think this is related to `babel-loader`. So you need to use beta version of it.
https://github.com/babel/babel-loader#install
