### ISSUE TITLE
Working with tests?

### ISSUE THREAD

**Issue by alexpriceonline** [ardatan/meteor-webpack#38]
I love the DX of using webpack here, but I can no longer run my tests with the `meteor test` command.  I'd been using the `meteortesting:mocha` driver for 6 months without issue until I changed to using webpack. Now I get the error:

```
Error: Cannot find module '/private/var/folders/3h/cm6yv0bs7xb_7h0_47p_w36h0000gn/T/meteor-test-run1qy5334.dlt1k/node_modules/webpack'
```

Any ideas how to get this up and running again? I'm happy to contribute if you point me in the right direction!

**Comment by ardatan** [comment]
Never tested with any testing package like `meteortesting:mocha`. It's supposed to handle the compiled code. So, you're welcome to contribute this project :) Thank you!

**Comment by powderham** [comment]
@alexpriceonline did you ever find a solution for this?

I cloned the repo, installed the package locally, passed a flag in my settings `testEnv` and then prevented `webpack-dev-middleware` from running. So whilst I didn't get an error, now I have no tests to run, I suspect that webpack is tree shaking them, or something similar so they're not checked
