### ISSUE TITLE
Error resolving module imports

### ISSUE THREAD

**Issue by aliogaili** [ardatan/meteor-webpack#4]
Thanks for the interesting package!

I'm running into the following error: 
```

ERROR in ./server/main.js
Module not found: Error: Can't resolve '/imports/startup/server' in '/Users/ali/Development/Meronex/Applications/Products/Meronex Communities/meronex-communities/server'
 @ ./server/main.js 1:0-33
 @ multi ./server/main.js
```
The ./server/main.js has the following line: 

`import '/imports/startup/server';
`

Any idea what might be causing this?  I think it might be due to the absolute paths since in the examples we've relative paths.

**Comment by aliogaili** [comment]
Ah I've the same setup and I'm also using .js extensions instead of .jsx.

However we're using absolute imports everywhere so it'll be major refactoring, perhaps I can test it on a smaller project until you do your refactoring.

**Comment by filipenevola** [comment]
I'm doing the same, starting on a smaller project, but if we can make it work, it'll be a major win for Meteor community :wink:

**Comment by ardatan** [comment]
Thank you for all your support :) I think same with you. Meteor community needs this kind of packages to keep Meteor alive and growing. 
After that, I will try to reproduce your problem. Also I am now working on creating test environment with Webpack and make this package support test tools like Karma etc.

**Comment by aliogaili** [comment]
Thanks @ardatan!

I'm curious though, how is this package different from the [existing older](https://atmospherejs.com/webpack/webpack) one on atmosphere?

**Comment by ardatan** [comment]
You can use `webpack.config.js` resolve configuration settings to use similar path in your imports.

**Comment by ardatan** [comment]
I am closing this issue. If you experience any problems, please open a new issue.

Thanks!

**Comment by jlmbaka** [comment]
Hi @ardatan, I am experiencing the same problème and I cannot seem to find the accepted solution to this problem. Can You tell me how to fix this problem ?

**Comment by filipenevola** [comment]
Hello @aliogaili and @jlmbaka, I'm able to use like this:
```
import AdminPage from 'imports/ui/containers/shared/admin-page';
```
with this setup on webpack
```

  resolve: {
    extensions: ['*', '.js', '.jsx'],
    alias: {
      imports: path.resolve(__dirname, 'imports/'),
    },
  },
```
I believe in your case you just need to find/replace all imports in your source code from `/imports/` to `imports/` (removing the first slash)
