### ISSUE TITLE
production ready?

### ISSUE THREAD

**Issue by mikaelwecode** [ardatan/meteor-webpack#7]
Hello! 

Thanks for creating this! The reload time with meteor is really annoying! specially for the frontend.

Just tried to migrate a medium sized meteor and react project. 
And it worked pretty good! (If I find som issue I will submit them. )

I was thinking if this is production ready? Can I make a production build? 

I use galaxy for my deploy.

**Comment by ardatan** [comment]
Thank you for your good comment and collaboration.
There are some known issues in development mode, but I didn't experience any problems in production mode. So you can try to use it with galaxy. If you experience any problems, please open an issue. I will help as soon as possible I can.

**Comment by mikaelwecode** [comment]
Ok. So I just make a production version off my webpack.config.js and it should be enough?

**Comment by ardatan** [comment]
You don’t need any extra config for production.

**Comment by mikaelwecode** [comment]
But when I run meteor deploy with --settings and with the same webpack.config.js (same as the react example). The react version is running in debug mode. 

Sorry, I dont know webpack so well. :)

**Comment by ardatan** [comment]
You're doing right :)

**Comment by mikaelwecode** [comment]
I had to set 

`new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production')
    })`

In the plugins array in config.js  :) 

and when deploy production to galaxy I hade to set NODE_ENV=production before the meteor deploy script! 

Thanks! :) 

I will keep trying more when there is time. Really love the idea with hotreload and webpack for Meteor!

**Comment by ardatan** [comment]
I am closing this issue. If you experience any issues in production, you can open a new issue about the case.

Thanks!
