### ISSUE TITLE
Accounts not working

### ISSUE THREAD

**Issue by promentol** [ardatan/meteor-webpack#76]
Meteor.loginWIthPassword methods is always returning an error. After debugging I see Accounts._loginHandlers is an empty array [], after server code push.

Here are the versions.
METEOR@1.8.1
ardatan:webpack@0.0.11
ardatan:webpack-dev-middleware@0.0.11
accounts-base@1.4.4
accounts-password@1.5.1

**Comment by stolinski** [comment]
Are you seeing the error `Unrecognized options for login request`? I’m getting that myself on every loginWithPassword call.

**Comment by promentol** [comment]
Yes, and I have solution

just in .meteor/packages, put  ardatan:webpack and ardatan:webpack-dev-middleware to the end of the file.
