### ISSUE TITLE
Examples are not working after new release

### ISSUE THREAD

**Issue by royGil** [ardatan/meteor-webpack#9]
The examples are not working, 

<img width="726" alt="39328339-5b51657e-499b-11e8-98d5-57419f4f74f1" src="https://user-images.githubusercontent.com/28781165/39400066-b2b199b4-4b31-11e8-8a1a-3a432ea6fbc0.png">

I could make it work by updating webpack and related packages to their latest version but then this error is thrown:

![screenshot from 2018-04-28 22-17-36 1](https://user-images.githubusercontent.com/28781165/39400111-d5c29150-4b32-11e8-9d21-844dbc492df2.png)

There are several points that should help us encounter the problem:

1. This error is thrown only when your server recompiles **after the inital compile**
2. Check out `Meteor.default_server.method_handlers` (on the server), you will see that it doesn't include methods that are set by meteor's packages (like accounts-password for example).
3. The problem didn't exist before introuducing HMR on the server.

any ideas?

### Update:

I found the problem [here](https://github.com/ardatan/meteor-webpack/blob/master/atmosphere-packages/webpack-dev-middleware/dev-server.js#L109).

```
// webpack-dev-middleare/dev-server

Meteor.server.method_handlers = {};
Meteor.server.publish_handlers = {};
```
Those two lines were basically deleting any handlers set by packages outside of our code.

I'm not sure why they exists so iv'e created a pull request (#10)  that keeps them there but make sure they are not overwriting anything important.

**Comment by ardatan** [comment]
Server-side HMR injects new server-side code with the same publications and methods; then existing ones make conflict. That's why, it deletes the existing ones.

**Comment by royGil** [comment]
Sorry but I'm not sure I understand you.
I was able to run everything correctly when iv'e used the change in the PR.

Meteor **does** include the publications and methods, but after it recompiles it's not including those who are loaded by **external packages** (i.e: accounts-password).

Did I miss anything?

**Comment by ardatan** [comment]
Meteor restarts the server in every change, but our package just injects the new code.
For example, you change your existing publication or method, our package will inject it; but Meteor will throw an error like `There is already a publication named 'todos'`. To prevent this, I was deleting all publications and methods.
Please let me know if it is clear.

**Comment by ardatan** [comment]
@royGil you're right, we need a solution for this problem as well :)

**Comment by royGil** [comment]
@ardatan
I'll investigate this abit and will update later..

Anything that comes to your mind about a proper solution?

**Comment by royGil** [comment]
Check #12 and let me know what you think.

**Comment by qqcky** [comment]
@ardatan Hi! Thank you for convenient way to use webpack for angular. I would like to use it in my project, but faced with same problem on Angular example. How can I avoid this issue?

**Comment by ardatan** [comment]
@qqcky Thank you for your interest :) Please feel free to open an issue about your problem
