### ISSUE TITLE
Help with automatically bundling sass files

### ISSUE THREAD

**Issue by schlaegerz** [ardatan/meteor-webpack#93]
I am attempting to move from the meteor build system to this package, but I am having trouble figure out how to automatically include the scss file like meteor does with fourseven:scss 

<id>.css?meteor_css_resource=true

I have tried including a sass-loader 
 {
          test: /\.s[ac]ss$/i,     
          use: ['style-loader','css-loader', 'sass-loader']        
 },

but I think I'm missing a step or two for it to work correctly.

I have a mid-sized app that I'm trying to migrate so I don't want to make any major changes to the code base, but this is one of my biggest blockers for moving over.

**Comment by ardatan** [comment]
This package replaces Meteor's build system with Webpack so you cannot mix other build plugins with Webpack's.
